import { Router } from "express";

const router = Router();

interface Trap {
  id: string;
  name: string;
  opening: string;
  description: string;
  side: "White" | "Black";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  moves: string[];
  trapMove: string;
  keyIdea: string;
  avoidance: string;
  fen: string;
}

const TRAPS: Trap[] = [
  {
    id: "scholars-mate",
    name: "Scholar's Mate",
    opening: "King's Pawn Opening",
    description: "The fastest possible checkmate in chess — delivered in just 4 moves. It targets f7, the weakest square near the enemy king before castling.",
    side: "White",
    difficulty: "Beginner",
    moves: ["1. e4 e5", "2. Bc4 Nc6", "3. Qh5 Nf6?", "4. Qxf7#"],
    trapMove: "4. Qxf7#",
    keyIdea: "Attack f7 simultaneously with your queen and bishop. The square is only defended by the king, and once your queen lands there — it's checkmate.",
    avoidance: "Play 3...g6 to push the queen back. Never leave f7 undefended in the opening with your queen side undeveloped.",
    fen: "r1bqkb1r/pppp1Qpp/2n2n2/4p3/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 0 4",
  },
  {
    id: "fools-mate",
    name: "Fool's Mate",
    opening: "King's Pawn / Bird's Opening",
    description: "The shortest possible game — only 2 moves. White weakens their own king's defenses and Black delivers checkmate instantly.",
    side: "Black",
    difficulty: "Beginner",
    moves: ["1. f3 e5", "2. g4?? Qh4#"],
    trapMove: "2...Qh4#",
    keyIdea: "If White irresponsibly opens the diagonal to their king with f3 and g4, Black's queen slides to h4 for instant checkmate.",
    avoidance: "Never play both f3 and g4 in the opening. Protect your king's diagonal at all times.",
    fen: "rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3",
  },
  {
    id: "legal-trap",
    name: "Légal's Trap",
    opening: "Philidor Defense",
    description: "A beautiful queen sacrifice that leads to smothered checkmate. White sacrifices the queen to deliver mate with minor pieces.",
    side: "White",
    difficulty: "Intermediate",
    moves: ["1. e4 e5", "2. Nf3 d6", "3. Bc4 Bg4", "4. Nc3 g6?", "5. Nxe5! Bxd1?", "6. Bxf7+ Ke7", "7. Nd5#"],
    trapMove: "5. Nxe5!",
    keyIdea: "After Black's bishop pins the knight, sacrifice your queen! If Black takes the queen, Bxf7+ forks the king, then Nd5 is smothered mate.",
    avoidance: "When you pin a piece, make sure the opponent can't profitably sacrifice through it. Always check for tactical responses.",
    fen: "rn1q1bnr/ppBbkNpp/8/3Np3/4P3/8/PPPP1PPP/R1BQK2R b KQ - 2 7",
  },
  {
    id: "blackburne-shilling",
    name: "Blackburne Shilling Gambit",
    opening: "Italian Game",
    description: "Black lures White into a greedy pawn grab, then launches a devastating counter-attack. Named because Blackburne allegedly won shillings from amateurs with this trick.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bc4 Nd4?!", "4. Nxe5? Qg5!", "5. Nxf7? Qxg2", "6. Rf1 Qxe4+", "7. Be2 Nf3#"],
    trapMove: "4...Qg5!",
    keyIdea: "After White greedily takes on e5, Black's queen forks the knight on e5 and the pawn on g2. White falls into a losing sequence.",
    avoidance: "After 3...Nd4, play 4. Nxd4 or 4. c3 instead of taking the pawn. Never be greedy in the opening.",
    fen: "r1b1kb1r/pppp1Npp/8/6q1/4n3/8/PPPPBPQP/RNB1KR2 w Qkq - 0 8",
  },
  {
    id: "elephant-trap",
    name: "Elephant Trap",
    opening: "Queen's Gambit Declined",
    description: "A classic trap in the QGD where White's bishop gets caught after an overly aggressive excursion. The bishop has no escape.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. d4 d5", "2. c4 e6", "3. Nc3 Nf6", "4. Bg5 Nbd7", "5. cxd5 exd5", "6. Nxd5? Nxd5!", "7. Bxd8? Bb4+", "8. Qd2 Bxd2+", "9. Kxd2 Kxd8"],
    trapMove: "6. Nxd5?",
    keyIdea: "White takes the pawn thinking the queen is hanging, but after Nxd5, if White takes the queen with Bxd8, Black plays Bb4+ winning back more than the queen.",
    avoidance: "Don't take on d5 if it allows Black's knight to jump in with tempo. Always calculate forcing sequences before capturing.",
    fen: "r1bk1b1r/pppn1ppp/8/3np3/1b6/8/PP1KPPPP/R3KBNR w KQ - 0 10",
  },
  {
    id: "noahs-ark-trap",
    name: "Noah's Ark Trap",
    opening: "Ruy López",
    description: "One of the oldest chess traps. Black's pawns advance to trap White's bishop — just as animals were trapped in the ark. The bishop has no escape.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bb5 a6", "4. Ba4 d6", "5. d4 b5", "6. Bb3 Nxd4", "7. Nxd4 exd4", "8. Qxd4? c5!", "9. Qd5 Be6", "10. Qc6+ Bd7", "11. Qd5 c4"],
    trapMove: "8...c5!",
    keyIdea: "After c5, the bishop on b3 is trapped by the advancing pawns. c4 will follow, and the bishop has nowhere to go.",
    avoidance: "In the Ruy Lopez, retreat your bishop to a safe square before Black can advance their queenside pawns to trap it.",
    fen: "r2qkb1r/3b1ppp/p2Q1n2/1pp5/2pp4/1B6/PPP2PPP/RNB1K2R w KQkq - 0 12",
  },
  {
    id: "lasker-trap",
    name: "Lasker Trap",
    opening: "Albin Counter-Gambit",
    description: "World Champion Emanuel Lasker's contribution. Black sacrifices material for a devastating attack, ending with a spectacular underpromotion to a knight!",
    side: "Black",
    difficulty: "Advanced",
    moves: ["1. d4 d5", "2. c4 e5", "3. dxe5 d4", "4. e3? Bb4+", "5. Bd2 dxe3!", "6. Bxb4?? exf2+!", "7. Ke2 fxg1=N+!", "8. Rxg1 Bh3"],
    trapMove: "7...fxg1=N+!",
    keyIdea: "Instead of promoting to a queen, promote to a KNIGHT! The knight forks king and rook, and Black wins material with a lasting attack.",
    avoidance: "In the Albin Counter-Gambit, avoid 4. e3 as it allows the d4 pawn to advance with tempo. Play 4. Nf3 instead.",
    fen: "rnbqk2r/ppp2ppp/7b/4P3/1B6/8/PP2K1PP/RNRN4 w kq - 0 9",
  },
  {
    id: "fishing-pole-trap",
    name: "Fishing Pole Trap",
    opening: "Ruy López / Berlin Defense",
    description: "Black dangles their knight like bait on a fishing pole, tempting White to take it — and walking into a devastating attack against the kingside.",
    side: "Black",
    difficulty: "Advanced",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bb5 Nf6", "4. 0-0 Ng4!", "5. h3? h5!", "6. hxg4? hxg4", "7. Ne1 Qh4", "8. f3 g3", "9. Rf2 gxf2+", "10. Kxf2 Qh2+"],
    trapMove: "4...Ng4!",
    keyIdea: "The knight on g4 tempts White to push h3. After h3, Black plays h5! and if White takes the knight, the h-file opens for a devastating attack.",
    avoidance: "After 4...Ng4, don't push h3. Instead play d4 or Re1 to maintain control. Never open lines toward your own king.",
    fen: "r1bqkb1r/pppp1pp1/2n5/4p3/4P2Q/5n2/PPPP1rPP/RNBK1BNR w kq - 0 11",
  },
  {
    id: "budapest-gambit-trap",
    name: "Budapest Gambit Trap",
    opening: "Budapest Gambit",
    description: "Black sacrifices a pawn to develop rapidly and spring a devastating attack on White's queen-side structure before White can consolidate.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. d4 Nf6", "2. c4 e5", "3. dxe5 Ng4", "4. Nf3 Bc5", "5. e3 Nc6", "6. Be2? Ngxe5", "7. Nxe5? Nxe5", "8. 0-0? Bxe3!"],
    trapMove: "8...Bxe3!",
    keyIdea: "After White castles too early, the bishop sacrifice on e3 blows open the position. White's king is fatally exposed after fxe3 Qh4+.",
    avoidance: "Against the Budapest Gambit, avoid castling before securing e3 with pieces. Develop solidly with 6. Bf4 or Bg5 to maintain the extra pawn.",
    fen: "r1bqk2r/pppp1ppp/2n5/4n3/2P5/4bN2/PP2BPPP/RNBQ1RK1 w kq - 0 9",
  },
  {
    id: "fried-liver-attack",
    name: "Fried Liver Attack",
    opening: "Two Knights Defense",
    description: "White sacrifices a knight on f7 to drag the Black king into the center and deliver a brutal attack. One of the most aggressive opening traps in chess.",
    side: "White",
    difficulty: "Advanced",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bc4 Nf6", "4. Ng5 d5", "5. exd5 Nxd5?", "6. Nxf7! Kxf7", "7. Qf3+ Ke6", "8. Nc3 Nce7", "9. d4! c6", "10. Bg5"],
    trapMove: "6. Nxf7!",
    keyIdea: "The knight sacrifice on f7 forces the king out. White then pours all pieces into the attack — Qf3+, Nc3, d4 — while Black's king wanders helplessly.",
    avoidance: "After 4. Ng5 d5, play 5...Na5 instead of 5...Nxd5 to avoid the Fried Liver. The knight can retreat to b3 without dropping the bishop.",
    fen: "r1bq1b1r/ppppNnpp/4k3/4P1B1/2BP4/2N5/PPP2PPP/R2QK2R b KQ - 2 10",
  },
  {
    id: "mortimer-trap",
    name: "Mortimer Trap",
    opening: "Ruy López (Berlin Defense)",
    description: "A sneaky counter-trap in the Ruy López Berlin Defense. After White plays the natural Nxe5, Black sets a subtle trap that wins a piece. White's most 'natural' follow-up loses immediately.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bb5 Nf6", "4. d3 Ne7?!", "5. Nxe5? c6!", "6. Bb4 Qa5+", "7. Nc3 Qxe5"],
    trapMove: "5...c6!",
    keyIdea: "After 4...Ne7 (the Mortimer Defense), White greedily takes the pawn with 5.Nxe5. But 5...c6! attacks the bishop AND threatens Qa5+ forking king and knight. White cannot save both the knight and the bishop — Black wins a piece.",
    avoidance: "As White, after 4...Ne7, play 5.Nc3 or 5.0-0 instead of 5.Nxe5. The 'free' e5 pawn is poisoned! Check all defensive resources before taking undefended pawns.",
    fen: "r1b1kb1r/pp1pnppp/2p5/4q3/1B2P3/2N5/PPP2PPP/R1BQK2R w KQkq - 0 8",
  },
  {
    id: "siberian-trap",
    name: "Siberian Trap",
    opening: "Sicilian Defense (Smith-Morra Gambit)",
    description: "A devastating counter-trap for Black in the Smith-Morra Gambit. Black appears to fall into a standard tactical fork, but it's White who walks into checkmate. The Siberian trap has claimed countless victims at club level.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. e4 c5", "2. d4 cxd4", "3. c3 dxc3", "4. Nxc3 Nc6", "5. Nf3 e6", "6. Bc4 Qc7", "7. 0-0 Nf6", "8. Qe2? Ng4!", "9. h3? Nd4!!", "10. hxg4? Nxe2+", "11. Kh1 Nxc3"],
    trapMove: "9...Nd4!!",
    keyIdea: "After White carelessly plays Qe2 and h3, Black's Nd4!! threatens Nxe2+ winning the queen AND Nxf3+ destroying the kingside. If White takes the knight with hxg4, Nxe2+ wins the queen with a fork. Black walks away with a decisive material advantage.",
    avoidance: "In the Smith-Morra Gambit, don't place the queen on e2 while the Ng4 is active and d4 is available for a knight. Play Qe1 or Re1 instead to avoid the Nd4 trick.",
    fen: "r1b1kb1r/ppqp1ppp/2p1p3/8/2B1P1P1/2n5/PP2nPP1/R1B2RK1 w kq - 0 12",
  },
  {
    id: "tarrasch-trap",
    name: "Tarrasch Trap",
    opening: "Queen's Gambit Declined",
    description: "A classic positional trap named after Siegbert Tarrasch. White provokes an early queen sally, then punishes it with a brilliant bishop sacrifice that traps the queen in the middle of the board. First played in 1892 — still catching victims today.",
    side: "White",
    difficulty: "Advanced",
    moves: ["1. d4 d5", "2. Nf3 Nf6", "3. c4 e6", "4. Bg5 Nbd7", "5. e3 c5", "6. Nc3 cxd4", "7. exd4 Be7", "8. Rc1 0-0", "9. Bd3 dxc4?!", "10. Bxc4 Nd5?", "11. Bxe7 Qxe7", "12. Bxd5! exd5", "13. Nxd5 Qd6", "14. Nxd5"],
    trapMove: "12. Bxd5!",
    keyIdea: "After Black takes on c4 and plays Nd5 — seemingly winning a piece — White's Bxd5! shatters the pawn structure. If Black takes with exd5, Nxd5 forks the queen and wins. Black's position collapses because the d5 square becomes a dominant outpost.",
    avoidance: "In the QGD, avoid the greedy ...dxc4 unless you've verified there's no tactical refutation. After ...Nd5, always check if the opponent can sacrifice on d5 or e7 to exploit the pin on the diagonal.",
    fen: "r1b2rk1/pp2qppp/3q4/3NN3/3P4/8/PP3PPP/R2QR1K1 b - - 0 14",
  },
  {
    id: "tennison-gambit",
    name: "Tennison Gambit Trap",
    opening: "Scandinavian / Tennison Gambit",
    description: "A wild and surprising gambit where White sacrifices a knight immediately to create a devastating attack. If Black accepts greedily, they walk into one of the fastest traps in chess history — often leading to checkmate in under 10 moves.",
    side: "White",
    difficulty: "Intermediate",
    moves: ["1. e4 d5", "2. Nf3 dxe4", "3. Ng5 Nf6?!", "4. Bc4 e6?", "5. Nxf7! Kxf7", "6. Qf3+ Ke6", "7. Nc3 Nc6", "8. Qe4 Ne5", "9. Bb3! c6", "10. f4 Ng6", "11. f5+! exf5", "12. Qxf5+ Ke7", "13. d4"],
    trapMove: "5. Nxf7!",
    keyIdea: "After Black develops too passively with ...Nf6 and ...e6, White sacrifices the knight on f7! The Black king is dragged into the open and faces a torrent of checks — Qf3+, Nc3, and a massive attack. Black's king cannot find safety.",
    avoidance: "Against the Tennison Gambit, Black should play 3...f5! (not 3...Nf6) to hold the extra pawn. If the gambit knight reaches f7, the resulting attack is extremely hard to defend over the board.",
    fen: "r1bq1b1r/pp4pp/2p1k1n1/3P1p2/3pP3/1BN5/PPP3PP/R1BQK2R b KQ - 0 13",
  },
  {
    id: "stafford-gambit",
    name: "Stafford Gambit Trap",
    opening: "Petrov's Defense",
    description: "One of the most dangerous amateur traps online. After 1.e4 e5 2.Nf3 Nf6 3.Nxe5, Black plays the Stafford Gambit with 3...Nc6!? — sacrificing a pawn for a devastating development lead. White must play accurately or walk into checkmate.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. e4 e5", "2. Nf3 Nf6", "3. Nxe5 Nc6?!", "4. Nxc6? dxc6", "5. d3? Bc5!", "6. Be2? Bxf2+!!", "7. Kxf2 Ng4+", "8. Kg1 Qd4+", "9. Kh1 Nxh2!!", "10. Kxh2? Qf2#"],
    trapMove: "6...Bxf2+!!",
    keyIdea: "After White greedily captures on c6 and plays passively with d3 and Be2, Black unleashes Bxf2+!! — a spectacular sacrifice. After Kxf2, Ng4+ Kg1 Qd4+ Kh1 Nxh2!! and White cannot avoid checkmate on h1 or f2.",
    avoidance: "Against the Stafford Gambit, play 4.Nc3! (not 4.Nxc6) to return the extra pawn and neutralize Black's attack. Or play 5.e4 (not d3) after taking on c6 to control the center. Never play Be2 if the Bc5 is aimed at f2.",
    fen: "r1b1k2r/ppp2ppp/2p5/8/3qP3/8/PPP1B1rP/RNBQ1RK1 w kq - 0 11",
  },
  {
    id: "budapest-gambit-trap",
    name: "Budapest Gambit Trap",
    opening: "Budapest Gambit",
    description: "After 1.d4 Nf6 2.c4 e5!?, Black offers a central pawn for rapid development. If White is greedy and tries to hold the extra pawn, Black unleashes a ferocious attack that often ends in a winning material advantage or a swift checkmate.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. d4 Nf6", "2. c4 e5", "3. dxe5 Ng4", "4. Bf4? Nc6", "5. Nf3? Bb4+", "6. Nbd2? Qe7!", "7. a3? Ngxe5!", "8. Nxe5? Nxe5", "9. e3? Bxd2+", "10. Qxd2 Nd3#"],
    trapMove: "10...Nd3#",
    keyIdea: "Black lures White into trying to keep the extra pawn with Bf4 and Nf3. After Bb4+ forces the knight to d2, Qe7 prepares a discovered attack. When Black plays Ngxe5 and White captures, Bxd2+ wins the queen and Nd3 is checkmate!",
    avoidance: "Against the Budapest Gambit, the correct move is 4.e4! (not Bf4), firmly keeping the extra pawn with a strong center. Avoid 4.Bf4 which lets Black begin a dangerous attack with Nc6 and Bb4+.",
    fen: "r1b1k2r/ppppqppp/8/4N3/1PP2B2/8/PP1bPPPP/R2QKB1R w KQkq - 0 10",
  },
  {
    id: "blackburne-shilling-trap",
    name: "Blackburne–Shilling Trap",
    opening: "Italian Game",
    description: "A cunning amateur trap in the Italian Game. Black invites White to take the e-pawn with the knight, setting up a devastating counter-attack with Nd4 that forks the queen and threatens Nxf3+ followed by smothered checkmate.",
    side: "Black",
    difficulty: "Beginner",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bc4 Nd4?!", "4. Nxe5? Qg5!", "5. Nxf7? Qxg2", "6. Rf1 Qxe4+", "7. Be2 Nf3#"],
    trapMove: "4...Qg5!",
    keyIdea: "After Nxe5, Black plays Qg5! — threatening both Qxg2 (winning the rook) and Qxe5 (winning the knight). If White greedily plays Nxf7, Black responds Qxg2 and ultimately delivers a beautiful smothered checkmate with Nf3#.",
    avoidance: "In the Italian Game, after 3...Nd4, White should simply play 4.Nxd4! (trading knights) or develop with 4.c3 to kick the knight — never fall for the greedy Nxe5 which walks into Qg5!",
    fen: "r1b1kbnr/pppp1N1p/8/6q1/2B1n3/8/PPPP1PrP/RNBQKR2 w Qkq - 0 8",
  },
  {
    id: "noahs-ark-trap",
    name: "Noah's Ark Trap",
    opening: "Ruy López (Spanish Opening)",
    description: "A classic positional trap from the Ruy López where Black uses connected pawns to trap and win White's prized bishop on c4. The trap is thousands of years old, yet still catches White players off guard in modern games.",
    side: "Black",
    difficulty: "Intermediate",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bb5 a6", "4. Ba4 Nf6", "5. O-O b5", "6. Bb3 d5", "7. exd5 Nxd5", "8. Nxe5? Nxe5", "9. d4 c5!", "10. dxe5 cxb4!", "11. c3 bxc3", "12. Nxc3 Nxc3", "13. bxc3 Bxb3", "14. axb3 Qd3"],
    trapMove: "9...c5!",
    keyIdea: "After White's greedy Nxe5, Black plays c5! — threatening the bishop and preparing the d5 pawn push. Black's pawn chain a6-b5-c4 entombs White's bishop, winning material. The bishop gets buried and cannot escape — just like in the biblical flood.",
    avoidance: "In the Ruy López after 6...d5, White should play 7.d4 or 7.d3 — not 8.Nxe5 after the exchange. White must be very careful with pawn breaks that allow Black's pawns to advance and trap the bishop.",
    fen: "r1b1kb1r/5ppp/p7/1p1pB3/8/1qP5/P4PPP/R1BQ1RK1 w kq - 0 15",
  },
  {
    id: "fried-liver-trap",
    name: "Fried Liver Attack",
    opening: "Two Knights Defense",
    description: "One of the most violent and feared attacks in chess — White sacrifices a knight on f7 to drag the Black king out into the open. The resulting attack is nearly impossible to defend without precise knowledge, making it a deadly weapon against unprepared opponents.",
    side: "White",
    difficulty: "Advanced",
    moves: ["1. e4 e5", "2. Nf3 Nc6", "3. Bc4 Nf6", "4. Ng5 d5", "5. exd5 Nxd5", "6. Nxf7!! Kxf7", "7. Qf3+ Ke6", "8. Nc3 Nce7?", "9. d4! exd4", "10. Bg5 c6", "11. O-O-O Kd7", "12. Nxd5 cxd5", "13. Bxd5 Nxd5", "14. Rxd5+ Kc6", "15. Qe4+ Kb6", "16. Rd6+ Ka5", "17. b4+ Ka4", "18. Qc2#"],
    trapMove: "6. Nxf7!!",
    keyIdea: "The Fried Liver is built on the knight sacrifice Nxf7! — dragging the Black king to f7 where it faces Qf3+ and relentless pressure. The king has no shelter, White's pieces pour in, and checkmate cannot be stopped without precise defense.",
    avoidance: "Against the Fried Liver, Black should avoid 5...Nxd5 and instead play 5...Na5! to kick the Bc4. After 6.Bb5+ c6 7.dxc6 bxc6, Black gets compensation and avoids the infamous king hunt.",
    fen: "r1bq1b1r/ppp1k2p/4p3/3RB3/3QP3/2N5/PPP2PPP/R3K3 b Q - 0 17",
  },
];

router.get("/", (_req, res) => {
  res.json(TRAPS);
});

router.get("/:id", (req, res) => {
  const trap = TRAPS.find((t) => t.id === req.params["id"]);
  if (!trap) {
    res.status(404).json({ error: "Trap not found" });
    return;
  }
  res.json(trap);
});

export default router;
